# GENERATED: This file is auto-generated by the code generation system
# Do not edit this file directly. Instead, modify entity_mappings / OpenAPI annotations
# and regenerate using: poetry run generate-registry

"""
Codegen-maintained model name → module path map.

Imported by ``congressgov.services.core.model_registry`` (hand-maintained registry class).
"""

from __future__ import annotations

# model class name -> dotted module path (class must exist in that module)
MODEL_PATH_MAP: dict[str, str] = {
    "Actions": "congressgov.models.actions.action",
    "Amendment": "congressgov.models.entities.amendment",
    "Amendments": "congressgov.models.entities.amendment",
    "Bill": "congressgov.models.entities.bill",
    "Bills": "congressgov.models.entities.bill",
    "BoundCongressionalRecord": "congressgov.models.documents.bound_congressional_record",
    "BoundCongressionalRecords": "congressgov.models.documents.bound_congressional_record",
    "CRSReport": "congressgov.models.documents.crs_reports",
    "CRSReports": "congressgov.models.documents.crs_reports",
    "Committee": "congressgov.models.committees.committee",
    "CommitteeMeeting": "congressgov.models.meetings.meeting",
    "CommitteeMeetings": "congressgov.models.meetings.meeting",
    "CommitteePrint": "congressgov.models.documents.committee_print",
    "CommitteePrints": "congressgov.models.documents.committee_print",
    "CommitteeReport": "congressgov.models.documents.committee_report",
    "CommitteeReports": "congressgov.models.documents.committee_report",
    "Committees": "congressgov.models.committees.committee",
    "Congress": "congressgov.models.entities.congress",
    "Congresses": "congressgov.models.entities.congress",
    "CongressionalRecord": "congressgov.models.documents.congressional_record",
    "DailyCongressionalRecord": "congressgov.models.documents.congressional_record",
    "Hearing": "congressgov.models.documents.hearing",
    "Hearings": "congressgov.models.documents.hearing",
    "HouseCommunication": "congressgov.models.communications.house_communication",
    "HouseCommunications": "congressgov.models.communications.house_communication",
    "HouseRequirement": "congressgov.models.communications.house_requirement",
    "HouseRequirements": "congressgov.models.communications.house_requirement",
    "HouseVote": "congressgov.models.communications.house_vote",
    "HouseVotes": "congressgov.models.communications.house_vote",
    "Member": "congressgov.models.entities.member",
    "Members": "congressgov.models.entities.member",
    "Nomination": "congressgov.models.nominations.nomination",
    "Nominations": "congressgov.models.nominations.nomination",
    "SenateCommunication": "congressgov.models.communications.senate_communication",
    "SenateCommunications": "congressgov.models.communications.senate_communication",
    "Summaries": "congressgov.models.entities.bill",
    "Treaties": "congressgov.models.entities.treaty",
    "Treaty": "congressgov.models.entities.treaty",
}

CODEGEN_ENTITY_NAMES: tuple[str, ...] = (
    "Bill",
    "Actions",
    "Amendment",
    "Summaries",
    "Congress",
    "Member",
    "HouseVote",
    "Committee",
    "CommitteeReport",
    "CommitteePrint",
    "CommitteeMeeting",
    "Hearing",
    "CongressionalRecord",
    "DailyCongressionalRecord",
    "BoundCongressionalRecord",
    "HouseCommunication",
    "HouseRequirement",
    "SenateCommunication",
    "Nomination",
    "CRSReport",
    "Treaty",
)