# GENERATED: This file is auto-generated by the code generation system
# Do not edit this file directly. Instead, modify the OpenAPI specification
# and regenerate using: poetry run generate-all

"""
Query and convenience methods for the HouseVote and HouseVotes models.

These methods are dynamically registered on the HouseVote and HouseVotes classes,
keeping the model files clean and focused on data validation.

The query builder (HouseVotesQuery) is created using the generic
CollectionQuery class from _query_builder.py, eliminating the
need for custom query class implementations.


Methods registered on HouseVotes (collection):
- Query methods: filter(), query(), group_by()
- List as plain list: query().to_list()
- Python protocols: __iter__, __len__, __getitem__, __bool__, __repr__ (collections_registry)

"""
from __future__ import annotations

from typing import TYPE_CHECKING

from ._query_builder import create_query_builder
from ._registry import register_method

# Import for type hints only (avoids circular imports at runtime)
if TYPE_CHECKING:
    from congressgov.models.communications.house_vote import HouseVote, HouseVotes

# Import the actual classes for registration
import congressgov.models.communications.house_vote as housevote_module
from congressgov.models.communications.house_vote import HouseVote, HouseVotes

# ========================================
# CREATE QUERY BUILDER WITH FIELD MAPPINGS
# ========================================

# NOTE: Create the HouseVotesQuery class using the generic query builder
# NOTE: Field mappings enable shorthand queries (e.g., type="hr" matches "HR")
# NOTE: item_class enables field validation to catch typos early
HouseVotesQuery = create_query_builder(
    collection_class=HouseVotes,
    items_field="houseRollCallVotes",
    item_class=HouseVote,
    field_mappings={},
)

# NOTE: Set it on the module so it can be imported
housevote_module.HouseVotesQuery = HouseVotesQuery

# NOTE: Make it available for use in this module
if not TYPE_CHECKING:
    globals()["HouseVotesQuery"] = HouseVotesQuery


# ========================================
# QUERY BUILDER ACCESS
# ========================================


@register_method(HouseVotes)
def query(self):
    """
    Get query builder for chaining operations.

    Example:
        items.query().filter(field="value", lazy=True).order_by("field").execute()

    Returns:
        Query builder instance for this collection
    """
    return HouseVotesQuery(self.houseRollCallVotes or [])


# ========================================
# CONVENIENCE METHODS
# ========================================


@register_method(HouseVotes)
def filter(self, *, lazy: bool = False, **kwargs):
    """
    Filter items by field values.

    Args:
        lazy: If True, return query builder. If False, return model instance (keyword-only).
        **kwargs: Field-value pairs to filter by.

    Returns:
        HouseVotes object (if eager) or HouseVotesQuery (if lazy)

    Examples:
        # Eager (default)
        filtered = items.filter(field="value")

        # Lazy (for chaining)
        filtered = items.filter(field="value", lazy=True).order_by("field").execute()
    """
    return self.query().filter(lazy=lazy, **kwargs)


@register_method(HouseVotes)
def group_by(self, field: str):
    """
    Group items by field value.

    Args:
        field: Field name to group by

    Returns:
        Dictionary mapping field values to HouseVotes instances

    Example:
        by_field = items.group_by("field")
        # Returns: {"value1": HouseVotes(...), "value2": HouseVotes(...)}
    """
    return self.query().group_by(field)
